#🚀 Day 4 — Item-Based Collaborative Filtering

Yesterday:

Find similar USERS

Today:

Find similar MOVIES

This is a VERY important shift.

And actually:

more scalable

more stable

widely used in industry


than user-based filtering.


---

🧠 First Understand WHY User-Based Has Problems

Suppose:

100 million users

new users join constantly

user preferences change frequently


Then:

user-user similarity becomes expensive

because users are dynamic.


---

🎯 Industry Observation

Movies/products change slowly.

Example:

Batman movie similarity remains mostly stable

iPhone similarity remains stable


So instead of:

finding similar users

companies often do:

finding similar items


---

🔥 CORE IDEA OF DAY 4

Instead of:

Users similar to you liked this

we now do:

People who liked THIS movie
also liked THESE movies

Example:

liked Batman

system recommends:

Superman

Spider-Man

Dark Knight



because similar users liked them together.


---

🎬 This Is Literally:

Amazon:

Customers also bought

Netflix:

Because you watched

YouTube:

Related videos



---

🚀 STEP 1 — Create User-Movie Matrix

Same as Day 3.

import pandas as pd

ratings_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_csv('../data/ml-100k/u.data', sep='\t', names=ratings_cols)

movie_cols = ['movie_id', 'title']
movies = pd.read_csv(
    '../data/ml-100k/u.item',
    sep='|',
    header=None,
    encoding='latin-1',
    usecols=[0,1],
    names=movie_cols
)

df = pd.merge(ratings, movies, on='movie_id')

user_movie_matrix = df.pivot_table(
    index='user_id',
    columns='title',
    values='rating'
)

user_movie_matrix.head()


---

🧠 SAME MATRIX

User	Batman	Titanic	Matrix

U1	5	1	5
U2	4	1	4
U3	1	5	2



---

🔥 DAY 3 vs DAY 4 DIFFERENCE

Day 3:

Compare:

USER ↔ USER

Day 4:

Compare:

MOVIE ↔ MOVIE


---

🚀 STEP 2 — Select One Movie

Example:

batman_ratings = user_movie_matrix['Batman']

This gives:

User	Rating

U1	5
U2	4
U3	1


Meaning:

how users rated Batman


---

🚀 STEP 3 — Find Similar Movies

Now compare Batman ratings with ALL other movie ratings.

similar_movies = user_movie_matrix.corrwith(batman_ratings)


---

🧠 WHAT IS HAPPENING HERE?

Suppose:

User	Batman	Superman

U1	5	5
U2	4	4
U3	1	2


Pattern similar.

So:

Batman ≈ Superman

Correlation becomes high.


---

🚀 STEP 4 — Clean Results

corr_batman = pd.DataFrame(similar_movies, columns=['Correlation'])

corr_batman.dropna(inplace=True)

corr_batman.head()


---

🚀 STEP 5 — Sort Similar Movies

corr_batman.sort_values('Correlation', ascending=False).head(10)

Now you get:

Movie	Correlation

Superman	0.95
Dark Knight	0.93
Spider-Man	0.91



---

⚠️ IMPORTANT PROBLEM

Some movies may get:

high similarity from only 2 users

That’s unreliable.

Same problem as Day 2 popularity issue.


---

🚀 STEP 6 — Add Rating Counts

ratings_count = df.groupby('title')['rating'].count()

corr_batman = corr_batman.join(ratings_count)

corr_batman.columns = ['correlation', 'num_ratings']

corr_batman.head()


---

🚀 STEP 7 — Filter Weak Movies

corr_batman[corr_batman['num_ratings'] > 100] \
    .sort_values('correlation', ascending=False) \
    .head(10)

NOW recommendations become more reliable.


---

🧠 ENTIRE DAY 4 IN ONE SENTENCE

Item-based filtering means:

Find movies liked together by similar users.

That’s all.


---

🔥 WHY INDUSTRY LOVES ITEM-BASED FILTERING

Because:

movies stable

products stable

easier caching

scalable

recommendations faster


Instead of:

computing millions of user similarities repeatedly

companies precompute:

movie similarity matrix


---

🧠 MOST IMPORTANT CONCEPT TODAY

Day 3:

similar PEOPLE

Day 4:

similar ITEMS


---

🎯 Homework / Experiments


---

1️⃣ Try Different Movies

Try:

Star Wars

Titanic

Toy Story


Check:

recommended similar movies


---

2️⃣ Observe Weird Recommendations

Some recommendations may look strange.

Why?

Because:

sparse data

limited overlap

correlation instability


VERY important industry issue.


---

3️⃣ Try Different Thresholds

num_ratings > 50
num_ratings > 200

Observe:

reliability improves

recommendations reduce


Tradeoff.


---

🚀 Tomorrow (Day 5)

We’ll move to:

Matrix Factorization / SVD

This is where recommendation systems become REAL ML.

You’ll learn:

latent features

embeddings

dimensionality reduction

hidden preference learning


This is the foundation of:

Netflix Prize solutions

modern recommender systems

embedding-based recommendations


Huge day ahead.

In [1]:
import pandas as pd

In [2]:
rating_cols = [ 'user_id', 'movie_id', 'rating', 'timestamp' ]

ratings = pd.read_csv ( '../data/ml-100k/u.data', sep = '\t', names = rating_cols )

movie_cols = [ 'movie_id', 'title' ]

movies = pd.read_csv ( '../data/ml-100k/u.item', sep = '|', header = None, encoding = 'latin-1', usecols = [0, 1], names = movie_cols )

df = pd.merge ( ratings, movies, on = 'movie_id' )

user_movie_matrix = df.pivot_table ( index = 'user_id', columns = 'title', values = 'rating' )

user_movie_matrix.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN

In [3]:
# Movie < - > Movie relationship

# Selecting one movie

batman_ratings = user_movie_matrix['Evil Dead II (1987)']

similar_movies = user_movie_matrix.corrwith ( batman_ratings )  # Find similar movies

# Clean results (Just correlation with every movies list)

corr_batman = pd.DataFrame ( similar_movies, columns = ['Correlation'] )

corr_batman.dropna ( inplace = True )

corr_batman.head()

C:\Users\Mugundhan\ML_Learning\recommendation_system\venv_ml\Lib\site-packages\numpy\lib\_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\Mugundhan\ML_Learning\recommendation_system\venv_ml\Lib\site-packages\numpy\lib\_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\Mugundhan\ML_Learning\recommendation_system\venv_ml\Lib\site-packages\numpy\lib\_function_base_impl.py:3015: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\Mugundhan\ML_Learning\recommendation_system\venv_ml\Lib\site-packages\numpy\lib\_function_base_impl.py:2888: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\Mugundhan\ML_Learning\recommendation_system\venv_ml\Lib\site-packages\numpy\lib\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

                             Correlation
title
1-900 (1994)                    0.944911
101 Dalmatians (1996)           0.046099
12 Angry Men (1957)            -0.023520
187 (1997)                      0.801784
2 Days in the Valley (1996)    -0.298327

In [4]:
# Sort similar movies

corr_batman.sort_values ( 'Correlation', ascending = False ).head(10)

                                 Correlation
title
Infinity (1996)                          1.0
Hunted, The (1995)                       1.0
I Like It Like That (1994)               1.0
Waiting to Exhale (1995)                 1.0
Hard Eight (1996)                        1.0
Harlem (1993)                            1.0
Boys of St. Vincent, The (1993)          1.0
Boy's Life 2 (1997)                      1.0
Browning Version, The (1994)             1.0
Blink (1994)                             1.0

In [5]:
# Add Rating counts

ratings_count = df.groupby ( 'title' )[ 'rating' ].count()

corr_batman  = corr_batman.join ( ratings_count )

corr_batman.columns = [ 'correlation', 'num_ratings' ]

corr_batman.head()

                             correlation  num_ratings
title
1-900 (1994)                    0.944911            5
101 Dalmatians (1996)           0.046099          109
12 Angry Men (1957)            -0.023520          125
187 (1997)                      0.801784           41
2 Days in the Valley (1996)    -0.298327           93

In [6]:
# Filter weak movies

corr_batman [ corr_batman [ 'num_ratings' ] > 100 ]. sort_values ( 'correlation', ascending = False ).head()

                            correlation  num_ratings
title
Little Women (1994)            0.701140          102
Peacemaker, The (1997)         0.681621          136
Army of Darkness (1993)        0.642986          116
Rumble in the Bronx (1995)     0.620990          174
Mother (1996)                  0.597246          169

YESSS 🔥
This is actually one of the MOST IMPORTANT observations in recommendation systems.

And what you discovered is a REAL industry problem.

You are seeing:

bad correlations due to sparse data

Let’s deeply understand WHY this happened.


---

🎯 What Happened Before Filtering?

You got:

Movie	Correlation

random drama movie	1.0
random romcom	1.0


for:

Evil Dead 2 (1987)

which makes NO logical sense.

Correct observation.


---

🧠 WHY Did This Happen?

Because:

very few users rated BOTH movies

Example:

Suppose ONLY 2 users rated:

User	Evil Dead 2	Random Drama

U1	5	5
U2	1	1


Pattern identical.

Correlation becomes:

1.0

PERFECT correlation.

BUT:

only 2 users participated

sample too tiny

statistically meaningless



---

🔥 THIS IS CALLED:

Spurious Correlation

Meaning:

mathematically high correlation
but practically meaningless

VERY common in sparse systems.


---

🧠 WHY FILTERING FIXED IT

After:

num_ratings > 100

you forced system to use:

popular movies with enough data

Now:

more users overlap

correlation becomes stable

recommendations become more realistic


That’s why second output looks MUCH better.


---

🔥 IMPORTANT INDUSTRY LESSON

Raw collaborative filtering is:

EXTREMELY noisy

Without filtering:

random correlations dominate

sparse overlaps create fake similarity

recommendations become weird


That’s why production systems use:

thresholds

confidence scores

regularization

matrix factorization

embeddings



---

🧠 What Your Output ACTUALLY Means

Before filtering:

math trusted tiny overlaps too much

After filtering:

system trusts movies with enough evidence

BIG difference.


---

🎯 WHY Evil Dead 2 Specifically Failed

Horror/cult movies often:

have fewer ratings

attract niche audiences

have sparse overlap


Sparse overlap → unstable correlation.

So:

small accidental patterns dominate


---

🔥 THIS IS EXACTLY WHY NETFLIX MOVED BEYOND BASIC CF

Simple correlation systems fail because:

sparse data

noise

scalability

fake correlations


So industry evolved toward:

matrix factorization

latent embeddings

neural recommenders


Which is EXACTLY where you’re heading tomorrow.


---

🧠 MOST IMPORTANT INSIGHT FROM TODAY

Similarity alone is NOT enough.

Need:

similarity + sufficient evidence

That’s why:

num_ratings > threshold

became critical.


---

🚀 Congratulations

You just discovered one of the BIGGEST practical problems in recommendation systems THROUGH experimentation.

That is REAL learning.